### PR TITLE
add @unused.

### PR DESCRIPTION
**Pull request by VladPodilnyk**
Solves: https://github.com/scala/scala-collection-compat/issues/369

### CODE REVIEW

**Comment by SethTisue** [comment]
Thank you!

CI is failing because you need sign the Scala CLA before we could accept this:

```
Please sign the Scala CLA to contribute to scala/scala-collection-compat
Go to https://www.lightbend.com/contribute/cla/scala
```

**Comment by VladPodilnyk** [comment]
Thanks for guiding me!
I've signed the CLA, but I guess it need some time to process an application. Do I need to trigger the build manually then?

**Comment by SethTisue** [comment]
I've restarted CI.

**Comment by SethTisue** [comment]
Does this actually work on 2.11 and 2.12, or is does providing it just prevent cross-compilation from failing?

**Comment by VladPodilnyk** [comment]
it should work on 2.11/2.12, l've tested and haven't spotted a warning for `unused variable`.

**Comment by SethTisue** [comment]
Thank you!

**Pull request merged**
