### PR TITLE
Add `toIntOption` (and `Long`, `Boolean`, et al)

### LINKED ISSUE #554: Add `.toXOption` methods from `StringOps`
There are some useful method in scala2.13.x, such as toLongOption, But it throws an NPE when the string is null, so probably not many people use it?

### PR DESCRIPTION
**Pull request by rjolly**
fixes #554

### CODE REVIEW

**Comment by SethTisue** [comment]
looked at this with Raphael just now and some work items remain:

* [ ] move the code to the `scala_2.11_2.12` folder (hopefully a separate 2.11 version won't be needed)
* [ ] refactor to remove the duplication of `assertThrow*`

**Comment by SethTisue** [comment]
perhaps @martijnhoekstra, the original author, would look to like once this is in final form

**Comment by SethTisue** [comment]
Looks like JS needs to expect a different exception:

```
[error] Test scala.collection.compat.StringParsersTest.nullDouble failed: Wrong exception: expected java.lang.NullPointerException but was scala.scalajs.js.JavaScriptException, took 0.002524921 sec
[58](https://github.com/scala/scala-collection-compat/actions/runs/3417699470/jobs/5689134821#step:5:59)
```

**Comment by SethTisue** [comment]
as for Native,

```
[error] Test scala.collection.compat.StringParsersTest.floatSpecificTest failed: str.toFloat <> str.toFloatOption for NaNd, took 0.009 sec
[69](https://github.com/scala/scala-collection-compat/actions/runs/3417699470/jobs/5689134943#step:5:70)
[error] Test scala.collection.compat.StringParsersTest.doubleSpecificTest failed: str.toDouble <> str.toDoubleOption for NaNd, took 0.009 sec
```

**Comment by rjolly** [comment]
Seems like both JS and Native think that "NaNd" should parse, as opposed to JVM.

**Review by SethTisue — APPROVED** [review]

**Review by lrytz — APPROVED** [review]

**Comment by SethTisue** [comment]
thank you @rjolly!

**Pull request merged**
