### PR TITLE
Rewrite `mutable.Set/Map` no longer have a `+` operation

### PR DESCRIPTION
**Pull request by MasseGuillaume**
motivation:
https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes

3nd row, breaking change

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
Yup it will require this fix: https://github.com/scala/scala-collection-compat/pull/53/commits/4c51cf37d48c9bf649565736c5b7b3d32eccfb23

**Comment by MasseGuillaume** [comment]
hum, actually it's fine. I did not find any counter examples.

**Comment by julienrf** [comment]
Can you still add the examples to the input file? Also you have to resolve the conflict (I know this is boring…)

**Comment by MasseGuillaume** [comment]
@julienrf good to go.

**Pull request merged**
