### PR TITLE
mutable.Queue.enqueueAll

### PR DESCRIPTION
**Pull request by samzilverberg**
adding compat support for mutable.Queue.enqueueAll

immutable.Queue.enqueueAll support was added before in:
https://github.com/scala/scala-collection-compat/pull/304

so extending to mutable was pretty straight forward

did:

- code copmiles and tests are green on projects: compat211, compat212, compat213
- scalafmt is happy

### CODE REVIEW

**Comment by samzilverberg** [comment]
travis says i need to first 
```
Please sign the Scala CLA to contribute to scala/scala-collection-compat
```
so brb with a signature 😁

**Comment by samzilverberg** [comment]
most of travis build stages are green but then some seem to fail when checking for CLA:
https://travis-ci.org/github/scala/scala-collection-compat/jobs/678793556
```
Incoming pull request from https://github.com/scala/scala-collection-compat/pull/325
Pull request submitted by null
CLA check for null failed
```
null? what?

**Comment by samzilverberg** [comment]
the problem resolved itself after waiting some more.

**Comment by SethTisue** [comment]
thank you! apologies for the very long delay

**Pull request merged**
