### PR TITLE
Migrating to scalafix 0.6.X

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by julienrf** [comment]
Also, there is one failing scalafix test.

**Comment by olafurpg** [comment]
@julienrf The scalafix docs will continue to advertise v0.5 until there is a release of v0.6.0-RC1. Past week, I've been updating the scalafix.g8 template https://github.com/scalacenter/scalafix.g8/pull/7 and migrating scalafix builtin rules to use the `scalafix.v1` API. I hope to have RC1 out before next weekend, but all of my estimates so far have been far off so I can't promise anything.

**Comment by MasseGuillaume** [comment]
@olafurpg It's only possible to run the rule right now with my fork of scalafix.

**Comment by julienrf** [comment]
@MasseGuillaume I’ve merged it to the `scalafix-0.6` branch of this repository. Does that unblock you?

**Pull request closed without merging**
