### PR TITLE
Make ArraySeq extends IndexedSeqOptimized

### PR DESCRIPTION
**Pull request by RustedBones**
Make `ArraySeq[T]` extends `IndexedSeqOptimized[T, ArraySeq[T]]` so that operation expecting `CanBuildFrom[ArraySeq[_], T, ArraySeq[T]]` return specialized `ArraySeq[T]` instead of `IndexedSeq[T]`.

Without this, the following can't compile
```scala
val x = ArraySeq(1, 2)
val y = ArraySeq(3, 4)
val z: ArraySeq[Int] = x ++ y
```

### CODE REVIEW

**Comment by SethTisue** [comment]
@scala/collections ?

**Comment by RustedBones** [comment]
Any news on this one ?

**Comment by SethTisue** [comment]
@lrytz @julienrf maybe one of you would like to review this...?

**Review by julienrf — APPROVED** [review]
That looks good to me, and it should also bring performance improvements!

**Pull request merged**
