### PR TITLE
Rewrite Map.mapValues -> Map.mapValues.toMap

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
@julienrf one step at a time. Let's implement everything in #57 then I can split them in #56

**Comment by julienrf** [comment]
I think it’s simpler to first address #56 but I’m fine as long as both approaches are eventually consistent.

**Comment by julienrf** [comment]
I will merge this one, can you fix the conflict?

**Comment by MasseGuillaume** [comment]
:heavy_check_mark:

**Pull request merged**
