### PR TITLE
run scalafmt, fail build if there is a violation

### LINKED ISSUE #256: `scalafmt-test` doesn't fail the build
https://travis-ci.org/scala/scala-collection-compat/jobs/585968662 runs with `TEST_SCALAFMT=true` and prints

```
[error] Exception in thread "main" org.scalafmt.Error$MisformattedFile: /home/travis/build/scala/scala-collection-compat/compat/src/main/scala-2.11_2.12/scala/collection/compat/CompatImpl.scala is mis-formatted. 

[error] 	at org.scalafmt.cli.InputMethod$FileContents.write(InputMethod.scala:51)
```

but the travis build is still green.

### PR DESCRIPTION
**Pull request by robstoll**
- fixes #256

### CODE REVIEW

**Comment by robstoll** [comment]
first run failed due to some files which where not yet correctly formatted or in other words, the fix works :slightly_smiling_face:

**Comment by martijnhoekstra** [comment]
dear god, I'm a swine

**Comment by robstoll** [comment]
@julienrf resolved the conflicts, let me know in case something needs to be done in addition

**Comment by julienrf** [comment]
Thanks Robert :)

**Pull request merged**
