### PR TITLE
sigh, rename back to scala-collection-compat (and re-enable MiMa)

### PR DESCRIPTION
**Pull request by SethTisue**
reverts #327

### CODE REVIEW

**Comment by SethTisue** [comment]
MiMa is failing, but only on 2.11. I'm out of work time for today — I'll look into it tomorrow if nobody beats me to it.

**Comment by SethTisue** [comment]
The failure is due to the addition of `toMapExtensionMethods` in #341. #205 explains why it only fails on 2.11 (trait encoding difference). 

I believe we can filter this out because the trait in question, `PackageShared`, is `private[compat]`.

**Comment by SethTisue** [comment]
#362 has MiMa followups

**Comment by NthPortal** [comment]
@SethTisue I think that method should be moved directly into the package object (which duplicates it because there are separate files for 2.11 and 2.12, but there's not much to do about that). that's what we've been doing for other things

**Comment by SethTisue** [comment]
@NthPortal oops, I was going to look at that before release, but it slipped my mind. is it too late now, because bincompat?

**Comment by NthPortal** [comment]
I... don't know enough about bincompat to say what we should do

**Comment by SethTisue** [comment]
> I... don't know enough about bincompat to say what we should do

Before I think too hard about that, I'd like to understand why you are suggesting the method should be moved directly into the package object.

> which duplicates it because there are separate files for 2.11 and 2.12, but there's not much to do about that

I'm confused — isn't avoiding such duplication exactly what `PackageShared` is for?

**Comment by NthPortal** [comment]
the problem is, adding methods to `PackageShared` isn't binary compatible, I believe. cc @julienrf

**Comment by SethTisue** [comment]
ah, thanks for surfacing that. @julienrf @lrytz was I wrong to add the MiMa exclusion here?

**Comment by julienrf** [comment]
> was I wrong to add the MiMa exclusion here?

Indeed, the correct solution is to duplicate the implicit conversion into the 2.11 and 2.12 source trees, as April said in https://github.com/scala/scala-collection-compat/pull/356#issuecomment-689368290.

**Comment by NthPortal** [comment]
What is the correct thing to do now?

- move the method to the package objects, draft a new release ASAP, and make a note that the release was bad and shouldn't be used?
- leave it as is?
- have the method in both places?

**Comment by SethTisue** [comment]
> What is the correct thing to do now?

Let's discuss on #367

**Pull request merged**
