### PR TITLE
Backport LazyList

### PR DESCRIPTION
**Pull request by NthPortal**
Still TODO:

- [x] Fix compilation on 2.11
- [x] ~~Fix serialization~~

### CODE REVIEW

**Comment by NthPortal** [comment]
I wish I could mark this as WIP again, cuz boy is it not done.
help welcome

**Comment by julienrf** [comment]
@NthPortal Could you explain what remains to be done?

**Comment by NthPortal** [comment]
@julienrf port GC tests, and make all the tests pass in all versions (or comment out/fix those that can't due to compiler bugs that weren't fixed until 2.13)

**Comment by NthPortal** [comment]
if someone can take a look at the last two little bits and make them compile, that would be hugely appreciated

**Comment by NthPortal** [comment]
I've given up on getting the serialization test to work across versions. it will just have to be specific to certain versions (2.11 and 2.13 JVM)

**Comment by NthPortal** [comment]
it seems GC tests don't work on JS (idk why I missed this before). Is there a good way to let them run only on JVM? or can they be tweaked to use something other than `Thread.sleep`?

**Comment by NthPortal** [comment]
The docs for `System.gc()` say that when the method returns, the GC will already have been run (to the extent the "best effort" could), so it's not clear to me that the `Thread.sleep(10)` is necessary at all.

However, even without the `Thread.sleep`, the tests for scala.js still fail (probably because `System.gc()` is a NOP in scala.js). While JS engines *do* tend to have garbage collectors, there doesn't appear to be a way to manually invoke them (which is fair, from a browser design perspective).

**Comment by yannbolliger** [comment]
The fix for this is here: https://github.com/NthPortal/scala-collection-compat/pull/1

**Comment by julienrf** [comment]
Thank you both!

**Comment by nilskp** [comment]
Do we know when this will be released?

**Comment by julienrf** [comment]
Hey, we should indeed cut a release soon, thanks for asking :smiley: 
I think it would be good to have Lukas’ work in it. Let’s wait for a couple of weeks to see if we manage to merge it.

**Comment by lrytz** [comment]
Is there a reason not to release often? It's little work, we have everything automated, no?

**Comment by julienrf** [comment]
I think last time we had an issue and had to manually publish things. But I agree that in principle we could release more often.

**Pull request merged**
