### PR TITLE
Upgrade Scala.js to 1.0.0

### PR DESCRIPTION
**Pull request by xerial**
Finally Scala.js 1.0.0 has been released https://github.com/scala-js/scala-js/releases/tag/v1.0.0

### CODE REVIEW

**Comment by xerial** [comment]
Looks like there is a bootstrap issue: for building scala-collection-compat, we need the version 2.1.3 built for Scala.js 1.0.0.

**Comment by xerial** [comment]
By setting a git tag (e.g., v2.1.4 for sbt-dynver), all tests (sbt test) worked on my local machine.

**Comment by julienrf** [comment]
Most likely, you need to do something like that: https://github.com/scala/scala-collection-compat/pull/268/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR19

**Comment by xerial** [comment]
@julienrf Thanks. Added a temporary workaround to pass the CI

**Comment by sjrd** [comment]
Thanks for the PR and for merging it.

Who can do the necessary steps to publish a version with 1.0.0 support? Some other libraries in the ecosystem are blocked by scala-collection-compat.

**Comment by SethTisue** [comment]
@julienrf are you planning to do a release shortly? if not, I can attempt it

**Comment by julienrf** [comment]
Hey all. I was offline for the end of the week. I was planning to do the release tomorrow.

**Comment by julienrf** [comment]
It seems that the release process went smoothly! Please let me know if something doesn’t work as expected. https://github.com/scala/scala-collection-compat/releases/tag/v2.1.4

**Comment by xerial** [comment]
@julienrf I still can't find 2.1.4 jar files for sjs1.0 jar in https://repo1.maven.org/maven2/org/scala-lang/modules/

Did you close and promote the staging artifacts at Sonatype? If you did that, we may need to wait for more hours until the artifacts will be synchronized at Sonatype.

**Comment by lrytz** [comment]
@xerial @julienrf I just released the staging repos, the artifacts will hopefully be on maven central soon.

**Comment by xerial** [comment]
Thanks! The artifacts are now available on Maven central.
cc: @sjrd

**Comment by xerial** [comment]
@lrytz 2.1.4 for Scala 2.12 is still misisng. https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/

**Comment by julienrf** [comment]
According to the CI logs they have been pushed to sonatype. @lrytz Do you still see these repositories?

**Comment by SethTisue** [comment]
there are no leftover staging repositories :-/

**Comment by xerial** [comment]
The above CI log only shows closing step. It looks like 2.1.4 for Scala 2.12 has never been promoted (sonatypePromote) or dropped before sonatypePromote step.

**Comment by lrytz** [comment]
I re-did the 2.1.4 for 2.12 release, the artifacts are there now https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.1.4/

**Pull request merged**
