### PR TITLE
Cross publish to scala 3.0.0-M3

### PR DESCRIPTION
**Pull request by cquiroz**
I think this PR should allow to publish `scala-collection-compat` for both M2 and M3

### CODE REVIEW

**Comment by ekrich** [comment]
Gosh, wouldn't it be easier to just bump the Scala version to M3 and then get a new version published.

**Comment by cquiroz** [comment]
Possibly. I'm guessing having M2/M3 maybe useful. At any rate it is failing in travis

**Comment by ekrich** [comment]
This library is very fast at publishing new versions. Surprisingly, I am seeing a `RC1` - https://repo1.maven.org/maven2/org/scala-lang/

**Comment by SethTisue** [comment]
let's go with #403

**Pull request closed without merging**
