### PR TITLE
No longer bundle as OSGi

### PR DESCRIPTION
**Pull request by lrytz**
As discussed at https://github.com/scala/scala-collection-compat/pull/312#issuecomment-614076407

### CODE REVIEW

**Comment by ijuma** [comment]
Thanks for doing this. Will there be another release of this soon?

**Comment by lrytz** [comment]
Yes, I'll do one early next week.

**Comment by ijuma** [comment]
Thank you!

**Comment by lrytz** [comment]
https://github.com/scala/scala-collection-compat/releases/tag/v2.1.6 is released and on maven central

**Comment by ijuma** [comment]
Thanks!

**Pull request merged**
