### PR TITLE
Scala 2.13.4 (was 2.13.3)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
@NthPortal CI shows a `LazyList` related test failure, but on Scala.js only — can interest you into looking into what that's about...?

**Comment by NthPortal** [comment]
We need to wait for a version of Scala.js build with 2.13.4 is published before that test will work for Scala.js

**Comment by SethTisue** [comment]
@sjrd are you planning on rolling a new Scala.js version?

**Comment by sjrd** [comment]
The next version will probably be around mid January, about 2 months after the latest release. Definitely not before the week is January 4, as I'm on vacation until then.

**Comment by SethTisue** [comment]
SGTM

**Pull request merged**
